<!--
===========================================================
Placed at the end of the document so the pages load faster
===========================================================
-->
<!-- MAIN JAVASRCIPT (REQUIRED ALL PAGE)-->
<script src="{{ asset('/js/jquery.min.js') }}"></script>
<script src="{{ asset('/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('/plugins/retina/retina.min.js') }}"></script>
<script src="{{ asset('/plugins/nicescroll/jquery.nicescroll.js') }}"></script>
<script src="{{ asset('/plugins/slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('/plugins/backstretch/jquery.backstretch.min.js') }}"></script>

<!-- PLUGINS -->
<!--
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
-->
<script src="{{ asset('/plugins/skycons/skycons.js') }}"></script>
<!--
A Javascript module and CSS file that allows syntax highlighting of source code snippets in an html page.
-->
<script src="{{ asset('/plugins/prettify/prettify.js') }}"></script>
<!--
Magnific Popup is a responsive lightbox & dialog script with focus on performance and providing best experience for user with any device
(for jQuery or Zepto.js).
-->
<script src="{{ asset('/plugins/magnific-popup/jquery.magnific-popup.min.js') }}"></script>
<!--
Touch enabled jQuery plugin that lets you create beautiful responsive carousel slider.
-->
<script src="{{ asset('/plugins/owl-carousel/owl.carousel.min.js') }}"></script>
<!--
Chosen is a jQuery plugin that makes long, unwieldy select boxes much more user-friendly.
-->
<script src="{{ asset('/plugins/chosen/chosen.jquery.min.js') }}"></script>
<!--
Highly customizable checkboxes and radio buttons (jQuery & Zepto)
http://fronteed.com/iCheck
-->
<script src="{{ asset('/plugins/icheck/icheck.min.js') }}"></script>
<script src="{{ asset('/plugins/datepicker/bootstrap-datepicker.js') }}"></script>
<script src="{{ asset('/plugins/timepicker/bootstrap-timepicker.js') }}"></script>
<!--
A jQuery Plugin to make masks on form fields and HTML elements.(按照指定的格式来格式化 input 里面的输入)
-->
<script src="{{ asset('/plugins/mask/jquery.mask.min.js') }}"></script>
<script src="{{ asset('/plugins/validator/bootstrapValidator.min.js') }}"></script>
<script src="{{ asset('/plugins/datatable/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('/plugins/datatable/js/bootstrap.datatable.js') }}"></script>
<!--
Super simple WYSIWYG Editor using Bootstrap.
http://summernote.org/
-->
<script src="{{ asset('/plugins/summernote/summernote.min.js') }}"></script>
<!--
A Markdown parser for javascript
-->
<script src="{{ asset('/plugins/markdown/markdown.js') }}"></script>
<!--
An HTML to Markdown converter written in JavaScript
http://domchristie.github.io/to-markdown
-->
<script src="{{ asset('/plugins/markdown/to-markdown.js') }}"></script>
<script src="{{ asset('/plugins/markdown/bootstrap-markdown.js') }}"></script>
<!--
进度条什么的，很强大
-->
<script src="{{ asset('/plugins/slider/bootstrap-slider.js') }}"></script>
<!--
Simple javascript toast notifications
-->
<script src="{{ asset('/plugins/toastr/toastr.js') }}"></script>

<!-- FULL CALENDAR JS -->
{{--<script src="{{ asset('/plugins/fullcalendar/lib/jquery-ui.custom.min.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/fullcalendar/fullcalendar/fullcalendar.min.js') }}"></script>--}}
{{--<script src="{{ asset('/js/full-calendar.js') }}"></script>--}}

<!-- EASY PIE CHART JS -->
{{--<script src="{{ asset('/plugins/easypie-chart/easypiechart.min.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/easypie-chart/jquery.easypiechart.min.js') }}"></script>--}}

<!-- KNOB JS -->
<!--[if IE]>
{{--<script type="text/javascript" src="{{ asset('/plugins/jquery-knob/excanvas.js') }}"></script>--}}
<![endif]-->
{{--<script src="{{ asset('/plugins/jquery-knob/jquery.knob.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/jquery-knob/knob.js') }}"></script>--}}

<!-- FLOT CHART JS -->
{{--<script src="{{ asset('/plugins/flot-chart/jquery.flot.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/flot-chart/jquery.flot.tooltip.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/flot-chart/jquery.flot.resize.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/flot-chart/jquery.flot.selection.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/flot-chart/jquery.flot.stack.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/flot-chart/jquery.flot.time.js') }}"></script>--}}

<!-- MORRIS JS -->
{{--<script src="{{ asset('/plugins/morris-chart/raphael.min.js') }}"></script>--}}
{{--<script src="{{ asset('/plugins/morris-chart/morris.min.js') }}"></script>--}}

<!-- C3 JS -->
{{--<script src="{{ asset('/plugins/c3-chart/d3.v3.min.js') }}" charset="utf-8"></script>--}}
{{--<script src="{{ asset('/plugins/c3-chart/c3.min.js') }}"></script>--}}

<!-- MAIN APPS JS -->
<script src="{{ asset('/js/apps.js') }}"></script>
<script src="{{ asset('/js/demo-panel.js') }}"></script>

<!-- SEA JS -->
<script src="{{ asset('/js/seajs/sea.js') }}"></script>
<script src="{{ asset('/js/config.js') }}"></script>
<script>
    @if(isset($load_js))
    seajs.use("{{ $load_js }}");
    @endif
</script>
